# Generated by Django 2.0.2 on 2018-05-15 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=255, unique=True, verbose_name='关键词')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
            },
        ),
        migrations.CreateModel(
            name='Searchs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=255, unique=True, verbose_name='搜索词')),
            ],
            options={
                'verbose_name': '用户搜索',
                'verbose_name_plural': '用户搜索',
            },
        ),
        migrations.CreateModel(
            name='WebInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(default='', max_length=255, unique=True, verbose_name='网站域名')),
                ('title', models.CharField(default='', max_length=255, verbose_name='网站标题')),
                ('keywords', models.TextField(default='', max_length=255, verbose_name='网站关键词')),
                ('desc', models.TextField(default='', max_length=255, verbose_name='网站描述')),
                ('create_time', models.DateField(default=datetime.datetime.now, verbose_name='收录时间')),
            ],
            options={
                'verbose_name': '网站信息',
                'verbose_name_plural': '网站信息',
            },
        ),
    ]
